/*
* These tokens are used for authentication with the Epic Games API.
* @module clientTokens
* @type {object}
*/
module.exports = {

    // Mobile client tokens
    ANDROID_TOKEN: "M2Y2OWU1NmM3NjQ5NDkyYzhjYzI5ZjFhZjA4YThhMTI6YjUxZWU5Y2IxMjIzNGY1MGE2OWVmYTY3ZWY1MzgxMmU=",
    IOS_TOKEN: "YWY0M2RjNzFkZDkxNDUyMzk2ZmNkZmZiZDdhOGU4YTk6NFlYdlNFQkxGUlBMaDFoekdaQWtmT2k1bXF1cEZvaFo=",

    // PC client token
    PC_TOKEN: "ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ=",

    // Console client tokens
    PS4_TOKEN: {
        EU: "NzlhOTMxYjM3NTMzNDU3MGFjMzY5MjM0ZjVkYTA1ZWM6ZWU3MzM1ZGYzYzRhNDEyY2I1NzA1NWFiN2FkZTY5M2U=",
        US: "ZDg1NjZmMmU3ZjVjNDhmODk2ODMxNzNlYjUyOWZlZTE6MjU1YzcxMDljODI3NDI0MTk4NjYxNmUzNzAyNjc4YjU"
    },
    SWITCH_TOKEN: {
        S1: "NTIyOWRjZDNhYzM4NDUyMDhiNDk2NjQ5MDkyZjI1MWI6ZTNiZDJkM2UtYmY4Yy00ODU3LTllN2QtZjNkOTQ3ZDIyMGM3CQ==",
        S2: "OThmN2U0MmMyZTNhNGY4NmE3NGViNDNmYmI0MWVkMzk6MGEyNDQ5YTItMDAxYS00NTFlLWFmZWMtM2U4MTI5MDFjNGQ3"
    },
    XBOX_TOKEN: "ZGI4NGZhNThiNjBlNDY4YmE2NGUzYjE3MjA5YjU2ZTk6MzMyODgxZDctZTU4Ni00NjgxLWIyNWItMzc3YTZkOTdkMjRk"

}